"""comment

Revision ID: 149a93d9cd98
Revises: 26f924ac2dd0
Create Date: 2025-11-01 15:21:09.663372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149a93d9cd98'
down_revision = '26f924ac2dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adv_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adv_command', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adv_command_created_at'), ['created_at'], unique=False)

    op.create_table('advanced_command_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advanced_command_id', sa.Integer(), nullable=True),
    sa.Column('adv_command_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adv_command_id'], ['adv_command.id'], ),
    sa.ForeignKeyConstraint(['advanced_command_id'], ['advanced_command.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advanced_command_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advanced_command_version_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('advanced_command', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))

    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nested_command', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ui_duration_unit', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('ui_verify_collapsed', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.drop_column('ui_verify_collapsed')
        batch_op.drop_column('ui_duration_unit')

    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.drop_column('nested_command')

    with op.batch_alter_table('advanced_command', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('advanced_command_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advanced_command_version_created_at'))

    op.drop_table('advanced_command_version')
    with op.batch_alter_table('adv_command', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adv_command_created_at'))

    op.drop_table('adv_command')
    # ### end Alembic commands ###
