"""add advanced command and user role

Revision ID: 26f924ac2dd0
Revises: 84f6feddc2c3
Create Date: 2025-10-16 03:15:32.288261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f924ac2dd0'
down_revision = '84f6feddc2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('base_commands', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('advanced_command', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advanced_command_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_advanced_command_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('advanced_command', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advanced_command_created_at'))
        batch_op.drop_index(batch_op.f('ix_advanced_command_category'))

    op.drop_table('advanced_command')
    # ### end Alembic commands ###
