"""add robot battery and location

Revision ID: a1b2c3d4e5f6
Revises: 149a93d9cd98
Create Date: 2025-11-05 03:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '149a93d9cd98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('battery', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robot', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('battery')

    # ### end Alembic commands ###
