"""add llm preferences to user

Revision ID: d7e8f9a0b1c2
Revises: c50c092eb5c0
Create Date: 2025-12-03

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e8f9a0b1c2'
down_revision = 'c50c092eb5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_provider', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('llm_model', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('llm_model')
        batch_op.drop_column('llm_provider')
    # ### end Alembic commands ###
