"""Engagement Phase 1

Revision ID: c50c092eb5c0
Revises: a1b2c3d4e5f6
Create Date: 2025-11-06 03:14:28.568033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50c092eb5c0'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('total_commands', sa.Integer(), nullable=True),
    sa.Column('total_advanced_commands', sa.Integer(), nullable=True),
    sa.Column('total_robots', sa.Integer(), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_points'), ['points'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profile_points'))
        batch_op.drop_index(batch_op.f('ix_user_profile_level'))
        batch_op.drop_index(batch_op.f('ix_user_profile_created_at'))

    op.drop_table('user_profile')
    # ### end Alembic commands ###
